# Generated by Django 3.0.5 on 2024-02-29 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='artist_name',
            field=models.CharField(max_length=1000, verbose_name='歌手'),
        ),
        migrations.AlterField(
            model_name='music',
            name='composer',
            field=models.CharField(max_length=1000, verbose_name='作曲'),
        ),
        migrations.AlterField(
            model_name='music',
            name='lyricist',
            field=models.CharField(max_length=1000, verbose_name='作词'),
        ),
        migrations.AlterField(
            model_name='music',
            name='song_name',
            field=models.CharField(max_length=1000, verbose_name='歌曲名称'),
        ),
    ]
