# Generated by Django 3.0.5 on 2024-03-01 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_auto_20240229_2212'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='url',
            field=models.CharField(default='https://m701.music.126.net/20240301234259/3c4c6553837086cd21eb6013475d9d05/jdymusic/obj/wo3DlMOGwrbDjj7DisKw/27978919250/663c/4088/7b7a/0c48207cb013f953f46fe2da7dd7f803.mp3', max_length=1000, verbose_name='歌曲链接'),
        ),
    ]
